version: "3.9"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my_backend
    restart: always
    depends_on:
      - redis
    environment:
      REDIS_ADDR: "redis:6379"
      DATABASE_URL: "root:jarindeveloper@tcp(34.87.36.121:3306)/linebk?parseTime=true"
      JWT_SECRET: "secret"
      ACCESS_TOKEN_EXPIRED: "15h"
      REFRESH_TOKEN_EXPIRED: "24h"
      JWT_ISSUER: "line-bk"
      X_API_KEY: "123"
      PORT: "8000"
    ports:
      - "8000:8000"

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always

volumes:
  redis_data:
