version: "3.9"
services:
  db:
    image: mysql:8
    container_name: my_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d

#   backend:
#     build: ./backend
#     container_name: my_backend
#     restart: always
#     depends_on:
#       - db
#     environment:
#       DATABASE_URL: "mysql://myuser:mypassword@db:3306/mydatabase"
#     ports:
#       - "8080:8080"

volumes:
  mysql_data:
